# -*- coding: utf-8 -*-
"""HW6_Q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RAq2kp7YR7JRvAiIo7FVKsLtTzf9U89y
"""

import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans

"""Using the Senate Votes dataset demo’ed in Lecture 11"""

url_votes = 'https://raw.githubusercontent.com/exemplary-citizen/PCA-and-Senate-Voting-Data/master/senator_pca_problem/senator_data_pca/'
senator_df =  pd.read_csv(url_votes + 'data_matrix.csv',error_bad_lines=False)
af = pd.read_csv(url_votes + 'politician_labels.txt', header=None)
af["affiliations"] = af[0].str.split().str[-1]

X = np.array(senator_df.values[:, 3:].T, dtype='float64') 
typical_row = X[0,:]
# print(typical_row.shape)
# print(typical_row)

k = 2
kmeans = KMeans(n_clusters=k, random_state=0)
kmeans.fit(X)
ans = kmeans.labels_
print(ans)
temp = af["affiliations"]
# print(temp)
for idx in range(len(temp)):
  if temp[idx] == 'Red':
    temp[idx] = 0
  elif temp[idx] == 'Blue':
    temp[idx] = 1
  
# print(temp)
# print(len(temp))
wrong_senator = []
for i in range(len(temp)):
  if ans[i] != temp[i]:
    wrong_senator.append(i)

print(f'wrong senator number are:{wrong_senator}')